### ISSUE TITLE
[RESEARCH] High memory consumption after frang configuration

### ISSUE THREAD

**Issue by ykargin** [tempesta-tech/tempesta#2098]
# Motivation

After frang configuration in [PR 598](https://github.com/tempesta-tech/tempesta-test/pull/598) tests started to fail with

```
 [ 6570.228871] ksoftirqd/0: page allocation failure: order:9, mode:0x40a20(GFP_ATOMIC|__GFP_COMP), nodemask=(null),cpuset=/,mems_allowed=0
 [ 6570.229960] CPU: 0 PID: 12 Comm: ksoftirqd/0 Tainted: G           OE     5.10.35.tfw-04d37a1 #1
 [ 6570.230476] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.15.0-0-g2dd4b9b3f840-prebuilt.qemu.org 04/01/2014
 [ 6570.231459] Call Trace:
 [ 6570.231964]  dump_stack+0x74/0x92
 [ 6570.232458]  warn_alloc.cold+0x7b/0xdf
```
Research needed

Test to reproduce - `tls/test_tls_integrity.ManyClients` and `tls/test_tls_integrity.ManyClientsH2` with `-T 1` option  and body > 16KB (8GB memory)

**Comment by krizhanovsky** [comment]
Looks like not enough memory.

**Comment by RomanBelozerov** [comment]
I receive meamleak for these tests and tempesta commit - 10b38e071bad93e87d5fab6d0213246d3b1b5c84. I used remote setup (Tempesta on a separate VM) and cmd `./run_tests.py -T 1 tls/test_tls_integrity.ManyClientsH2` with MTU 80. So I run this test with 16KB, 64KB and 200KB body and I see the usage of all available memory (6GB for my VM for Tempesta) and meamleak after test ~1GB

look like it is fixed in #2105. I cannot get meamleak for this PR, but I see the usage of all available memory. I think Tempesta uses an unexpected lot of memory in these tests. 10 clients with 64KB response/request body, python uses ~400MB, but Tempesta ~5GB, why?

**Comment by biathlon3** [comment]
Here we have the next situation for 64KB test.

In this test, Tempesta FW receives 65536 bytes of data request from 10 clients, routes them to a server, gets responds from a server and sends them to the clients.
With option -T 1, each request and respond are split by byte.
The key point is that if Tempesta FW receives only one byte, it uses a full skb (about 900 bytes).

Tempesta FW receives at least 655360 skbs from clients, it is 655360 * 900 = 589 824 000 bytes.
Tempesta FW makes copies of all skbs in ss_skb_unroll() because all skbs are marked as cloned. Since the original skbs are marked as SKB_FCLONE_CLONE, they are not freed after consume_skb() right at this point.

Next, before routing these skbs to the server Tempesta FW makes clones in ss_send() with the purpose of resending if something goes wrong.

After the server has responded, Tempesta FW receives the same amount of skbs as from the clients.
And as all skbs are marked as cloned, it makes copies of these skbs.

Here we have allocated at least 589 824 000 * 5 = 2 949 120 000 bytes and only after Tempesta FW starts sending responds to clients, it starts freeing skbs.

**Comment by krizhanovsky** [comment]
@biathlon3 thank you for the detailed analysis! I still have a couple of questions and appreciate your elaboration on them:

1. `skb_cloned()` in `ss_skb_unroll()` comes under `unlikely()` and IIRC this is because modern HW NICs form skbs with data in pages only (unfortunately, I don't remember why clones appear otherwise). So please research why clones appear in the network stack? Whether moving to a different virtual adapters (e.g. virtio-net or SR-IOV) helps to avoid the clones? Please see https://tempesta-tech.com/knowledge-base/Hardware-virtualization-performance/ . Since virtual environments aren't rare, probably we need to remove `unlikely` add comments to the code why clones appear and rework our wiki in recommendations for virtual environments.
2. What sk_buff spends 900 bytes for? Could you please write down how much memory which parts of SKB spend and which the Linux kernel compilation options may reduce the memory footprint. This probably can be documented in our wiki.

**Comment by biathlon3** [comment]
> What sk_buff spends 900 bytes for? Could you please write down how much memory which parts of SKB spend 

Empty skb immidiatelly after ss_skb_alloc(0) or received skb:
    sizeof(struct sk_buff) = 232
    hdr_len = 320
    sizeof(struct skb_shared_info) = 320

232 + 320 + 320 = 872 
Actually little bit more, the smalest truesize=896
