### ISSUE TITLE
sometimes `max_queued_control_frames` does not send a warning to dmesg

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#2126]
TempestaFW - 302ea8c35dde7b9a46825a66f67f841e1219a02a from PR #2108 

The `max_queued_control_frames` directive works correctly and client receive a connection block when  it breaks the rule.
But sometimes `Warning: Too many control frames in send queue, closing connection` warning may not be output to the dmesg

VM does not have limit for `net_ratelimit` and I didn't see any message suppression 
```shell
root@tempesta-test-6:~# cat /proc/sys/net/core/message_cost
0
```

I just receive 1 warning for these tests
```
Warning: request dropped: incorrect X-Forwarded-For header: 127.0.0.2
```
but expected
```
Warning: Too many control frames in send queue, closing connection
Warning: request dropped: incorrect X-Forwarded-For header: 127.0.0.2
```

# Testing

`http2_general.test_max_queued_control_frames.TestH2ControlFramesFlood.test_reset_stream_10_limit`,
`http2_general.test_max_queued_control_frames.TestH2ControlFramesFlood.test_ping`,
`http2_general.test_max_queued_control_frames.TestH2ControlFramesFlood.test_settings`,

there is 1 more test in this directory - `http2_general.test_max_queued_control_frames.TestH2ControlFramesFlood.test_reset_stream_default`, bit it does not reproduce this problem.
Please change expected number of warning in tests from `cond=lambda matches: len(matches) >= 0` to `cond=dmesg.amount_one`

**Comment by kingluo** [comment]
@RomanBelozerov 
The test case does not set the socket's rcvbuf size, so the default size can include a small number of control frame acks. Although asyncore stops reading, the underlying socket will continue reading until the sockbuf is full. Therefore, there is a high probability that the control frame acks are successfully transmitted to the client. It is better not to set such a small number of control frames. That's why the default size of 10000 succeeds, because it fills up the sockbuf.

**Comment by kingluo** [comment]
@RomanBelozerov @krizhanovsky @const-t 
I have to point out another common problem in tempesta-test: when we check the messages in the dmesg log, we don't distinguish the boundaries of test runs, so warning message assertions can be true due to messages from the previous test run, which is why these test cases pass, even though the message didn't actually appear in the current test run. It's better to have an incremental reading of the dmesg log to ensure the correct message assertion.

```python
        self.assertTrue(
            self.oops.find(
                "Warning: Too many control frames in send queue, closing connection",
                cond=lambda matches: len(matches) >= 0,
            ),
            "An unexpected number of dmesg warnings",
        )
```

**Comment by RomanBelozerov** [comment]
@kingluo
Yes, you were almost right. `max_queued_control_frames` works correctly. The problem was in the tests.

The main problem in these tests - deproxy thread does not have time to open connection and the main thread calls the `wait_for_connection_close` and `restart` for client. As a result, we do not receive a warning in dmesg. I fixed tests [here](https://github.com/tempesta-tech/tempesta-test/pull/615/commits/69fef4475355db80a9636053bc9b4b18be116942).

Also we have the problem with [warning](https://github.com/tempesta-tech/tempesta/blob/302ea8c35dde7b9a46825a66f67f841e1219a02a/fw/http_frame.c#L295). You should add `\n` to this warning to output the message to dmesg without delay.

I close issue because the problem was in tests and I fixed it.

**Comment by kingluo** [comment]
Sorry, I'm afraid this doesn't solve the problem.

As I mentioned above, response chunks for large responses are interleaved with control frame ACKs, so you cannot guarantee that enough chunks will be delivered before the control frame ACK to fill the deproxy client's sockbuf and ensure that the latter will block due to the TCP window becoming 0.

`client.readable = lambda: True` only [prevents asyncore from processing epoll read events](https://docs.python.org/3.11/library/asyncore.html#asyncore.dispatcher.readable), but does not prevent the linux kernel from reading data from the TCP socket. Control frame flooding is a slow read attack that relies on TCP-level read blocking.

So, the correct approach is to use `setsockopt()` to set a sockbuf small enough so that it is not large enough to hold all the control frame acknowledgments.

However, it takes time for the limit to trigger, so it is best to wait a few milliseconds to observe the warning message.

**Comment by RomanBelozerov** [comment]
Ok. I saw the tcpdump file and log file. But they is not correct because as I mentioned above, the tests did not work correctly. Please add `\n` to warning in TempstaFW and check new version of the tests.

**Comment by RomanBelozerov** [comment]
I reworked the tests using `socket.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 1024)`, but it does not work without filling the buffer. So I use this way:

1. set a small buffer for client; (it is needed for stability of tests. The different VMs have a different size of buffer);
2. request a large data from backend and disable socket for reading. Tempesta can not send any data to the client until the client enable socket for reading; 
3. wait until the client buffer is full; (this is needed to avoid interleaving of data frames and ping ACKs);
4. send number of attack frames (limit +10% for stability of test);
5. wait for connection close and warning from dmesg;

In this case we check that `max_queued_control_frames` limit works correctly. But we are not simulated attack
